const questionsData = [
  {
    "question_id": 1,
    "question": "What famous Roman general and statesman was assassinated on the Ides of March in 44 BC?",
    "answer_index": 0,
    "choices": ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    "hint": "He was also a renowned military commander.",
  },
  {
    "question_id": 2,
    "question": "What was the name of the ancient Roman currency?",
    "answer_index": 1,
    "choices": ["Sestertius", "Denarius", "Aureus", "As"],
    "hint": "It was a silver coin.",
  },
  {
    "question_id": 3,
    "question": "What famous building in Rome was originally built as a stadium for chariot races and other public events?",
    "answer_index": 1,
    "choices": ["The Colosseum", "Circus Maximus", "Pantheon", "Forum Romanum"],
    "hint": "It could hold up to 250,000 spectators.",
  },
  {
    "question_id": 4,
    "question": "What famous Roman emperor built a wall in northern Britain to protect against Scottish tribes?",
    "answer_index": 0,
    "choices": ["Hadrian", "Constantine", "Trajan", "Augustus"],
    "hint": "The wall is named after him.",
  },
  {
    "question_id": 5,
    "question": "What was the name of the first Roman emperor?",
    "answer_index": 3,
    "choices": ["Julius Caesar", "Tiberius", "Caligula", "Augustus"],
    "hint": "He was the nephew of Julius Caesar.",
  },
  {
    "question_id": 6,
    "question": "What was the name of the famous Roman road that ran from Rome to Brindisi?",
    "answer_index": 2,
    "choices": ["Via Appia", "Via Flaminia", "Via Traiana", "Via Aurelia"],
    "hint": "It was also known as the Appian Way.",
  },
  {
    "question_id": 7,
    "question": "What was the name of the famous Roman physician who wrote a famous medical text known as the 'Canon'?",
    "answer_index": 3,
    "choices": ["Galen", "Hippocrates", "Aristotle", "Avicenna"],
    "hint": "He was born in Persia (modern-day Iran).",
  },
  {
    "question_id": 8,
    "question": "What was the name of the famous Roman philosopher who wrote 'Meditations'?",
    "answer_index": 0,
    "choices": ["Marcus Aurelius", "Seneca", "Epictetus", "Plato"],
    "hint": "He was also a Roman emperor.",
  },
  {
    "question_id": 9,
    "question": "What was the name of the ancient Roman festival of Saturnalia?",
    "answer_index": 0,
    "choices": ["Saturnalia", "Lupercalia", "Fornacalia", "Consualia"],
    "hint": "It was held in honor of the god Saturn.",
  },
  {
    "question_id": 10,
    "question": "What was the name of the famous Roman poet who wrote the epic poem 'The Aeneid'?",
    "answer_index": 1,
    "choices": ["Horace", "Virgil", "Ovid", "Catullus"],
    "hint": "He lived during the reign of Augustus.",
  },
  {
    "question_id": 11,
    "question": "What was the name of the famous Roman statesman and orator known for his speeches against Mark Antony?",
    "answer_index": 2,
    "choices": ["Cato the Elder", "Marcus Licinius Crassus", "Cicero", "Lucius Cornelius Sulla"],
    "hint": "He was one of Rome's greatest orators.",
  },
  {
    "question_id": 12,
    "question": "What was the name of the ancient Roman goddess of love and beauty?",
    "answer_index": 1,
    "choices": ["Juno", "Venus", "Minerva", "Diana"],
    "hint": "She was the mother of Cupid.",
  },
  {
    "question_id": 13,
    "question": "What was the name of the famous Roman commander who defeated the Carthaginian general Hannibal in the Second Punic War?",
    "answer_index": 3,
    "choices": ["Scipio Africanus", "Julius Caesar", "Pompey", "Fabius Maximus"],
    "hint": "He was also known as Scipio the Elder.",
  },
  {
    "question_id": 14,
    "question": "What was the name of the famous Roman historian who wrote 'The Histories'?",
    "answer_index": 0,
    "choices": ["Tacitus", "Livy", "Suetonius", "Plutarch"],
    "hint": "He lived during the reigns of several emperors, including Nero and Trajan.",
  },
  {
    "question_id": 15,
    "question": "What was the name of the famous Roman emperor who famously said 'I found Rome a city of bricks and left it a city of marble'?",
    "answer_index": 2,
    "choices": ["Augustus", "Nero", "Titus", "Vespasian"],
    "hint": "He ruled from 14 AD to 37 AD.",
  },
  {
    "question_id": 16,
    "question": "What was the name of the famous Roman general who defeated the Greek city-state of Corinth in 146 BC and sacked the city?",
    "answer_index": 1,
    "choices": ["Pompey", "Lucius Mummius", "Gnaeus Domitius Ahenobarbus", "Scipio Aemilianus"],
    "hint": "He was also known for his patronage of the arts.",
  },
  {
    "question_id": 17,
    "question": "What was the name of the famous Roman emperor who issued the Edict of Milan, which granted religious tolerance to Christians in the Roman Empire?",
    "answer_index": 3,
    "choices": ["Trajan", "Hadrian", "Constantine", "Nero"],
    "hint": "He was also known for his military campaigns in the east.",
  },
  {
    "question_id": 18,
    "question": "What was the name of the famous Roman general who was defeated by Hannibal at the Battle of Cannae in 216 BC?",
    "answer_index": 1,
    "choices": ["Scipio Africanus", "Lucius Aemilius Paullus", "Publius Cornelius Scipio", "Gaius Flaminius"],
    "hint": "He was known for his innovative military tactics.",
  },
{
  "question_id": 19,
  "question": "What was the name of the famous Roman poet who wrote the 'Metamorphoses'?",
  "answer_index": 2,
  "choices": ["Lucretius", "Catullus", "Ovid", "Horace"],
  "hint": "He was exiled by the Roman emperor Augustus.",
},
  {
    "question_id": 20,
    "question": "What was the name of the famous Roman general who defeated the Egyptian forces of Cleopatra and Mark Antony in the Battle of Actium in 31 BC?",
    "answer_index": 0,
    "choices": ["Octavian (Augustus)", "Julius Caesar", "Pompey", "Antony"],
    "hint": "He became the first Roman emperor.",
  }
];
export default questionsData;